-- Maxify Multi-Vendor Marketplace Schema
-- Streamlined for AliExpress Import Integration

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT,
  url TEXT,
  description TEXT,
  compare_at_price NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access" ON products FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert" ON products FOR INSERT WITH CHECK (true);

